version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: career_counselling_portal/Dockerfile
    volumes:
      - ./career_counselling_portal:/app
    ports:
      - "9988:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "9999:5173"
    depends_on:
      - backend
    restart: unless-stopped
