FROM python:3.10-slim

WORKDIR /app

# ✅ Install system dependencies for psycopg2
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY career_counselling_portal/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 9988

CMD ["python", "manage.py", "runserver", "0.0.0.0:9988"]
